[package]
name = "orr_physics3d"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
orr_fp = { path = "../orr_fp" }
orr_ecs = { path = "../orr_ecs" }
orr_sim = { path = "../orr_sim" }
orr_reflect = { path = "../orr_reflect", default-features = false }
bytemuck = { version = "1", features = ["derive"] }

[dev-dependencies]
orr_reflect = { path = "../orr_reflect", default-features = false, features = ["scene"] }
orr_session = { path = "../orr_session" }
criterion = { version = "0.5", default-features = false }

[[bench]]
name = "physics3d"
harness = false
