//! AGENTS.md generation: an agent guide built from what the host reports,
//! so it is pinned to the engine version, build id and type registry it was
//! generated from.
//!
//! Inputs: `rpc.discover` (engine block, capabilities, value format),
//! `registry.types` and `registry.schema` (the types of the game), and the
//! tool list of this crate. The text is a pure function of them: no
//! timestamps, no addresses, no scene content. `docs/AGENTS.md` is the
//! output for the demo scene, and a test regenerates it.

use serde_json::Value as J;

use crate::bridge::{Bridge, Fail};
use crate::server::PROTOCOL_VERSION;
use crate::tools::{self, ToolGroups};

/// FNV-1a 64 of `text`, as the fingerprint of a schema.
fn fnv1a(text: &str) -> u64 {
    text.bytes().fold(0xcbf2_9ce4_8422_2325u64, |h, b| (h ^ u64::from(b)).wrapping_mul(0x0100_0000_01b3))
}

fn s(v: &J) -> &str {
    v.as_str().unwrap_or("")
}

/// The first sentence of `text` (up to the first period followed by a space, or the whole text).
fn first_sentence(text: &str) -> String {
    let flat: String = text.split_whitespace().collect::<Vec<_>>().join(" ");
    match flat.find(". ") {
        Some(i) => flat[..=i].to_string(),
        None => flat,
    }
}

/// Builds the guide by asking the host. `groups`: the tool groups the guide describes.
pub fn generate(bridge: &mut Bridge, groups: ToolGroups) -> Result<String, Fail> {
    let discover = bridge.call("rpc.discover", J::Null)?;
    let types = bridge.call("registry.types", J::Null)?;
    let schema = bridge.call("registry.schema", serde_json::json!({}))?;
    Ok(render(&discover, &types, &schema["schema"], groups))
}

/// Renders the guide from the three ERP results (no I/O).
pub fn render(discover: &J, types: &J, schema: &J, groups: ToolGroups) -> String {
    let engine = &discover["engine"];
    let fingerprint = fnv1a(&serde_json::to_string(schema).unwrap_or_default());
    let mut o = String::new();
    let mut line = |t: &str| {
        o.push_str(t);
        o.push('\n');
    };

    line("# Orrery: guide for AI agents");
    line("");
    line("<!-- Generated by `orr_mcp --print-agents-md` from a running host. Do not edit by hand. To regenerate this file: `ORR_UPDATE_AGENTS=1 cargo test -p orr_mcp --test agents_md`. -->");
    line("");
    line(&format!(
        "Pinned to: **{} {}** | ERP {} | MCP {} | build id `{}` | game `{}` | schema fingerprint `0x{fingerprint:016x}`",
        s(&engine["name"]),
        s(&engine["version"]),
        engine["erp_version"],
        PROTOCOL_VERSION,
        s(&engine["build_id"]),
        s(&engine["game"]),
    ));
    line("");
    line("If the host you talk to reports a different version, build id or schema fingerprint, this file may be out of date: trust the host (`get_schema`, `orrery://agents`) and regenerate the file with `orr_mcp --print-agents-md`.");
    line("");

    line("## What Orrery is");
    line("");
    line("Orrery is a deterministic, rollback-capable ECS game engine. A **scene** is a set of **entities** (each with a stable GUID such as `e_00000005` and an optional display name) that carry **components**, plus **singletons** (one value per type). The simulation uses fixed-point arithmetic only, so the same scene and the same inputs always produce the same checksums on every machine. That is what makes verification by replay exact.");
    line("");
    line("You work through MCP tools (`orr_mcp`), which talk to a running host (the editor, or the headless `orr_remote_host`) over ERP. Your edits go through the same document as a person's: they share one undo history, and each entry says who made it (`agent:<your client name>`).");
    line("");

    line("## The workflow: propose, verify, accept");
    line("");
    line("1. **Look.** `scene_overview` lists entities and their GUIDs; `get_entity` reads components; `get_schema` gives fields, ranges and docs of every type. Never guess a GUID or a field name.");
    line("2. **Propose.** `propose_changes` stages your edits on a private copy of the scene and returns a proposal id (`p1`), a unified diff and a summary. **The scene is not changed.** All ops of one call apply together or not at all. Add more ops with `proposal_id`.");
    line("3. **Verify.** `verify_proposal` runs the scene without and with your proposal, headlessly, on the same inputs, and compares checksums and **metrics**. Give `checks` to get pass/fail with reasons. A failing check means: fix the proposal (propose_changes with `proposal_id`) or `reject_proposal`.");
    line("4. **Accept.** `accept_proposal` applies the proposal as **one** undoable history entry. It needs the `approve` capability; if the host withheld it, tell the person to accept in the editor. If the scene changed meanwhile and an op no longer applies you get a conflict and nothing changes: propose again.");
    line("5. **Undo** (`undo`) takes the last history entry back exactly, whoever made it.");
    line("");
    line("A person may be editing at the same time and may make proposals too (`list_proposals`). Do not accept a proposal you have not verified.");
    line("");

    line("## Tools");
    line("");
    line(&format!("Tool groups on in this guide: {}. (`orr_mcp --tools scene,propose,verify` switches groups on and off.)", groups.names().join(", ")));
    line("");
    line("| Tool | Group | Needs | What it does |");
    line("|---|---|---|---|");
    for t in tools::defs(groups) {
        line(&format!("| `{}` | {} | `{}` | {} |", t.name, t.group, t.needs, first_sentence(t.description).replace('|', "\\|")));
    }
    line("");
    line("Resources: `orrery://scene` (the scene as YAML), `orrery://schema` (JSON Schema), `orrery://agents` (this guide).");
    line("");
    line("A tool that fails returns `isError: true` with the engine's message (with a hint what to do). Ids are strings: proposals `p1`, entities `e_...`.");
    line("");

    line("## Value format");
    line("");
    line(s(&discover["value_format"]));
    line("");
    line("Examples: a vector `[0, 12.5]`; a fixed-point number `-0.5` (write it as a plain decimal, never `1e-1`, never in quotes); an enum `\"dynamic\"`; an entity reference `\"e_00000005\"` or `null`; a tagged value `{ \"kind\": \"circle\", \"radius\": 0.5 }`. Numbers come back exact: `0.1` is stored as `0.1000061` (1/65536 steps), and a checksum is a string `0x` followed by 16 hex digits.");
    line("");

    line("## Types of this game");
    line("");
    line("Every field is required in the scene file, but a whole-component patch may list only some fields (the rest stay). `get_schema` with `type` gives the exact schema of one type.");
    line("");
    let empty = Vec::new();
    let defs = &schema["$defs"];
    for t in types["types"].as_array().unwrap_or(&empty) {
        let name = s(&t["name"]);
        line(&format!("### `{name}` ({})", s(&t["kind"])));
        line("");
        let doc = first_paragraph(s(&t["doc"]));
        if !doc.is_empty() {
            line(&doc);
            line("");
        }
        if let Some(def) = defs.get(name) {
            for l in field_lines(def, defs) {
                line(&l);
            }
            line("");
        }
    }

    line("## Verification");
    line("");
    line("`verify_proposal` runs both scenes for a number of ticks on **inputs**:");
    line("");
    line("| inputs | meaning |");
    line("|---|---|");
    line("| `{\"kind\":\"bot\",\"ticks\":300,\"seed\":1}` | scripted players (deterministic; another seed, another play). The default. |");
    line("| `{\"kind\":\"idle\",\"ticks\":300}` | no player input |");
    line("| `{\"kind\":\"last_play\"}` | the recording of the last play session stopped in this host (a person's play in the editor, or `sim_run`) |");
    line("| `{\"kind\":\"replay\",\"base64\":\"...\"}` | a `.orrp` recording |");
    line("");
    let v = &engine["verify"];
    line(&format!(
        "Limits: at most {} ticks per call; the run blocks the host, so use a few hundred ticks for quick answers. Tick rate {}, {} players by default. Scripted players: {}.",
        v["max_ticks"],
        v["tick_rate"],
        v["default_players"],
        if v["bot_available"] == true { "available" } else { "not available in this host (use idle, last_play or replay)" }
    ));
    line("");
    line("Every scene edit changes the checksums from tick 0, so `first_divergence` is 0 for a real change. **Judge behaviour by metrics and checks**, not by divergence. An unchanged run (`identical: true`) means the proposal has no effect on the simulation.");
    line("");
    line("### Checks");
    line("");
    line(&format!("Grammar: `{}`", s(&v["check_grammar"])));
    line("");
    line("- `<metric>.<stat> <cmp> <number>`: `stat` is `start` (before the first tick), `final` (after the last; the default), `min`, `max` (over the sampled ticks) or `delta` (candidate final minus base final). `cmp` is `<`, `<=`, `==`, `!=`, `>=` or `>`. A metric of the candidate run unless prefixed `base:`.");
    line("- `no_divergence`: checksums equal at every tick. `no_divergence_before <tick>`. `recording_matches`: the scene reproduces the recording's checksums (inputs `last_play` or `replay`).");
    line("");
    line("Examples: `lost_bodies.max == 0`, `mean_height >= 2.5`, `base:dynamic_bodies.start == 40`, `kinetic_energy.delta <= 10`, `entities.final == 49`.");
    line("");
    line("Omit `proposal_id` to run the scene alone: baseline numbers to choose sensible thresholds from.");
    line("");
    line("### Metrics");
    line("");
    line("Integer (`int`) or exact fixed-point (`fixed`) numbers sampled during the run.");
    line("");
    line("| metric | kind |");
    line("|---|---|");
    let metrics = engine["metrics"].as_array().unwrap_or(&empty);
    let mut counts: Vec<&str> = Vec::new();
    for m in metrics {
        let name = s(&m["name"]);
        match name.strip_prefix("components.") {
            Some(ty) => counts.push(ty),
            None => line(&format!("| `{name}` | {} |", s(&m["kind"]))),
        }
    }
    line("");
    if !counts.is_empty() {
        line(&format!("`components.<type>` (int) counts the entities that have a component type: {}.", counts.iter().map(|c| format!("`{c}`")).collect::<Vec<_>>().join(", ")));
        line("");
    }

    line("## Capabilities");
    line("");
    line("A host gives each token a set of capabilities; a tool refused for lack of one says which.");
    line("");
    line("| capability | allows |");
    line("|---|---|");
    line("| `read` | look at the scene, schema, proposals, history; verify (replay runs on copies) |");
    line("| `scene_edit` | make and change proposals, reject them, undo |");
    line("| `approve` | accept a proposal into the scene (a host may keep this for a person) |");
    line("| `sim_control` | start, step, seek and stop a play session |");
    line("");

    line("## Conventions and pitfalls");
    line("");
    line("- Name entities by GUID (from `scene_overview`), not by display name: names are not unique.");
    line("- Stay inside the ranges the schema states; an out-of-range or mistyped value is refused with the field named.");
    line("- Despawning an entity that another entity still points at is refused: change the reference first (same proposal).");
    line("- Keep proposals small and focused, one intent each, with a label that says what and why: the label becomes the history entry.");
    line("- After `accept_proposal`, `history` shows the entry as `agent:<your client name>`; `undo` reverts it exactly.");
    line("- While a play session runs (`sim_run`), the scene document cannot be accepted into or undone; stop the session first.");
    o
}

/// The first paragraph of a doc comment, on one line.
fn first_paragraph(doc: &str) -> String {
    let para: Vec<&str> = doc.split("\n\n").next().unwrap_or("").lines().map(str::trim).collect();
    para.join(" ").split_whitespace().collect::<Vec<_>>().join(" ")
}

fn ref_name(r: &str) -> &str {
    r.rsplit('/').next().unwrap_or(r)
}

fn range(schema: &J) -> String {
    match (schema.get("minimum"), schema.get("maximum")) {
        (Some(a), Some(b)) => format!(" [{a}, {b}]"),
        _ => String::new(),
    }
}

/// A compact type text for a JSON Schema fragment.
fn type_text(schema: &J, defs: &J) -> String {
    if let Some(r) = schema.get("$ref").and_then(J::as_str) {
        return match ref_name(r) {
            "orr.Fixed" => "fixed".to_string(),
            "orr.Fixed32" => "fixed32".to_string(),
            "orr.EntityRef" => "entity reference (GUID or null)".to_string(),
            other => match defs.get(other) {
                Some(d) if d.get("enum").is_some() || d.get("oneOf").is_some() => type_text(d, defs),
                _ => format!("`{other}`"),
            },
        };
    }
    if let Some(e) = schema.get("enum").and_then(J::as_array) {
        return format!("one of {}", e.iter().map(|v| format!("`{}`", s(v))).collect::<Vec<_>>().join(" | "));
    }
    if let Some(list) = schema.get("oneOf").and_then(J::as_array) {
        let parts: Vec<String> = list
            .iter()
            .map(|v| {
                let kind = v["properties"]["kind"]["const"].as_str().unwrap_or("?");
                let fields: Vec<&str> = v["properties"].as_object().map(|m| m.keys().map(String::as_str).filter(|k| *k != "kind").collect()).unwrap_or_default();
                if fields.is_empty() { format!("`{kind}`") } else { format!("`{kind}` {{{}}}", fields.join(", ")) }
            })
            .collect();
        return format!("tagged by `kind`: {}", parts.join("; "));
    }
    match schema.get("type").and_then(J::as_str) {
        Some("array") => {
            if let Some(items) = schema.get("prefixItems").and_then(J::as_array) {
                let n = items.len();
                if n == 2 || n == 3 {
                    return format!("vec{n}{}", items.first().map(range).unwrap_or_default());
                }
            }
            let inner = schema.get("items").map(|i| type_text(i, defs)).unwrap_or_else(|| "any".into());
            let bounds = match (schema.get("minItems"), schema.get("maxItems")) {
                (Some(a), Some(b)) => format!(" ({a} to {b})"),
                _ => String::new(),
            };
            format!("list of {inner}{bounds}")
        }
        Some("number") => format!("fixed{}", range(schema)),
        Some("integer") => format!("int{}", range(schema)),
        Some("boolean") => "bool".to_string(),
        Some("string") => "string".to_string(),
        Some("object") => "object".to_string(),
        _ => match schema.get("const") {
            Some(c) => format!("`{}`", s(c)),
            None => "any".to_string(),
        },
    }
}

/// `- field: type. doc` lines of a struct type (nothing for other kinds).
fn field_lines(def: &J, defs: &J) -> Vec<String> {
    let Some(props) = def.get("properties").and_then(J::as_object) else { return Vec::new() };
    props
        .iter()
        .map(|(name, p)| {
            let doc = first_paragraph(s(&p["description"]));
            let doc = if doc.starts_with("Fixed-point number") { String::new() } else { doc };
            if doc.is_empty() { format!("- `{name}`: {}", type_text(p, defs)) } else { format!("- `{name}`: {}. {doc}", type_text(p, defs)) }
        })
        .collect()
}
