//! AGENTS.md generation: an agent guide built from what the host reports,
//! so it is pinned to the engine version, build id and type registry it was
//! generated from. It is CLI-first (`orr`, crate `orr_cli`) with a short MCP
//! section at the end; `orr agents-md`, `orr_mcp --print-agents-md` and the
//! MCP resource `orrery://agents` all print this text.
//!
//! Inputs: `rpc.discover` (engine block, capabilities, value format),
//! `registry.types` and `registry.schema` (the types of the game), and the
//! tool list of this crate. The text is a pure function of them: no
//! timestamps, no addresses, no scene content. `docs/AGENTS.md` is the
//! output for the demo scene, and a test regenerates it.

use serde_json::Value as J;

use crate::bridge::{Bridge, Fail};
use crate::server::PROTOCOL_VERSION;
use crate::tools::{self, ToolGroups};

/// FNV-1a 64 of `text`, as the fingerprint of a schema.
fn fnv1a(text: &str) -> u64 {
    text.bytes().fold(0xcbf2_9ce4_8422_2325u64, |h, b| (h ^ u64::from(b)).wrapping_mul(0x0100_0000_01b3))
}

fn s(v: &J) -> &str {
    v.as_str().unwrap_or("")
}

/// The first sentence of `text` (up to the first period followed by a space, or the whole text).
fn first_sentence(text: &str) -> String {
    let flat: String = text.split_whitespace().collect::<Vec<_>>().join(" ");
    match flat.find(". ") {
        Some(i) => flat[..=i].to_string(),
        None => flat,
    }
}

/// Builds the guide by asking the host. `groups`: the tool groups the guide describes.
pub fn generate(bridge: &mut Bridge, groups: ToolGroups) -> Result<String, Fail> {
    let discover = bridge.call("rpc.discover", J::Null)?;
    let types = bridge.call("registry.types", J::Null)?;
    let schema = bridge.call("registry.schema", serde_json::json!({}))?;
    Ok(render(&discover, &types, &schema["schema"], groups))
}

/// Renders the guide from the three ERP results (no I/O).
pub fn render(discover: &J, types: &J, schema: &J, groups: ToolGroups) -> String {
    let engine = &discover["engine"];
    let arena = engine["game"] == "Arena";
    let input = engine.get("input").filter(|value| value["schema"].is_object());
    let fingerprint = fnv1a(&serde_json::to_string(schema).unwrap_or_default());
    let mut o = String::new();
    let mut line = |t: &str| {
        o.push_str(t);
        o.push('\n');
    };

    line("# Orrery: guide for AI agents");
    line("");
    line("<!-- Generated by `orr agents-md` from a running host. Do not edit by hand. To regenerate this file: `ORR_UPDATE_AGENTS=1 cargo test -p orr_mcp --test agents_md`. -->");
    line("");
    line(&format!(
        "Pinned to: **{} {}** | ERP {} | MCP {} | build id `{}` | game `{}` | schema fingerprint `0x{fingerprint:016x}`",
        s(&engine["name"]),
        s(&engine["version"]),
        engine["erp_version"],
        PROTOCOL_VERSION,
        s(&engine["build_id"]),
        s(&engine["game"]),
    ));
    line("");
    line("If the host you talk to reports a different version, build id or schema fingerprint (`orr status`, `orr schema --types`), this file may be out of date: trust the host and regenerate the file with `orr agents-md`.");
    line("");

    line("## What Orrery is");
    line("");
    line("Orrery is a deterministic, rollback-capable ECS game engine. A **scene** is a set of **entities** (each with a stable GUID such as `e_00000005` and an optional display name) that carry **components**, plus **singletons** (one value per type). The simulation uses fixed-point arithmetic only, so the same scene and the same inputs always produce the same checksums on every machine. That is what makes verification by replay exact.");
    line("");
    if arena {
        line("You work with the `orr` command line, a thin client of the headless Arena host (`orr_remote_host --game arena`) over ERP. Your edits go through the host's scene document: they share one undo history, and each entry says who made it (`agent:<your client name>`). Inspect changes with `orr activity` and `orr history`; check your change with `orr apply` and undo what turns out wrong.");
    } else {
        line("You work with the `orr` command line, a thin client of a running host (the editor, or the headless `orr_remote_host`) over ERP. Your edits go through the same document as a person's: they share one undo history, and each entry says who made it (`agent:<your client name>`). A person watching the editor sees what you do in its Agent tab; there is no approval step, so finish the job yourself: check your change with `orr apply` and undo what turns out wrong.");
    }
    line("");

    line("## Setup");
    line("");
    line("Start a host (once), then use `orr` from any shell:");
    line("");
    line("```sh");
    if arena {
        line("orr_remote_host --game arena --dev-no-auth           # headless Arena (no token: local development)");
        line("orr_remote_host --game arena --token claude:s3cret:all # Arena with a token (name:token:capabilities)");
    } else {
        line("orr_editor --erp 127.0.0.1:7777 --erp-dev          # the editor, with an ERP endpoint (no token: local development)");
        line("orr_remote_host --dev-no-auth                        # or headless, same address");
        line("orr_remote_host --token claude:s3cret:all             # a host that needs a token (name:token:capabilities)");
    }
    line("orr status                                            # is it there? game, mode, tick, checksum, proposals");
    line("```");
    line("");
    line("- Address: `--erp <url>` or `ORR_ERP` (also accepted: `ORR_ERP_URL`), default `ws://127.0.0.1:7777`.");
    line("- Token: `--token <t>` or `ORR_ERP_TOKEN` (prefer the environment: it stays out of the process list). No token = a host started in dev mode. `orr` never prints the token.");
    line("- `--json` on any command prints the raw structured result instead of text. `--name <agent>` is informational; the host's token decides the name in the history.");
    line("- `orr help` lists the commands; `orr help <command>` (or `orr <command> --help`) documents one with examples.");
    line("");

    line("## The workflow");
    line("");
    line("1. **Look first.** `orr status`; `orr scene` (entities, GUIDs, component types; `--filter <text>`, `--has <Type>`, `--components` for values); `orr get <entity> [Component.path]` (an entity is a GUID or an exact display name); `orr schema --types` and `orr schema <type>` for fields, ranges and docs. Never guess a GUID or a field name.");
    if arena {
        line("2. **Small edits: `orr set`.** `orr set hero Position.pos=[-300,0]` changes a discovered entity named hero at once; all assignments of one command are one undo entry. Also `orr spawn`, `orr despawn`, `orr rename`, `orr add`, `orr remove`.");
        line("3. **Anything non-trivial: `orr apply`.** `orr apply \"move hero\" set hero Position.pos=[-300,0] --idle 20 --check \"out_of_bounds.max == 0\"` stages the change on a private copy, replays the scene without and with it on the same inputs, judges your `--check` rules and accepts the change only if all pass. On a failed check it rejects the change, prints the report and exits 4 with the scene untouched (`--keep` leaves the proposal open to fix). This is the recommended way to change a scene.");
    } else {
        line("2. **Small edits: `orr set`.** `orr set body_05 Body.pos=[6,18] Body.angle=0.5` changes the scene at once; all assignments of one command are one undo entry. Also `orr spawn`, `orr despawn`, `orr rename`, `orr add`, `orr remove`.");
        line("3. **Anything non-trivial: `orr apply`.** `orr apply \"lift hero\" set hero Body.pos=[6,18] --check \"lost_bodies.max == 0\"` stages the change on a private copy, replays the scene without and with it on the same inputs, judges your `--check` rules and accepts the change only if all pass. On a failed check it rejects the change, prints the report and exits 4 with the scene untouched (`--keep` leaves the proposal open to fix). This is the recommended way to change a scene.");
    }
    line("4. **Step by step, when you need to look between the steps:** `orr propose <label> <ops...>` (nothing changes; prints the diff), `orr verify <pN> --check ...`, then `orr accept <pN>` or `orr reject <pN>`. `orr proposals` and `orr diff <pN>` show what is open; a person may make proposals too.");
    line("5. **Watch and undo.** `orr activity` (or `orr activity -f` to follow live) shows what every client did, with old and new values. `orr history` lists the undo history; `orr undo` takes the last entry back exactly, whoever made it; `orr redo` repeats it.");
    line("");
    line("Do not accept or apply what you have not verified. Keep changes small and focused, with a label that says what and why: the label becomes the history entry.");
    line("");

    line("## Commands");
    line("");
    line("| Command | What it does | Needs |");
    line("|---|---|---|");
    line("| `orr status` | host, game, build id, mode (edit or play), tick, checksum, unsaved changes, open proposals, connected clients | `read` |");
    line("| `orr scene [--components] [--filter t] [--has Type]` | entities and singletons | `read` |");
    line("| `orr get <entity> [Component[.path]]` | values in the scene format (`@Scene` reads a singleton) | `read` |");
    line("| `orr schema [type] \\| --types` | the value schema of the game's types | `read` |");
    if input.is_some() {
        line("| `orr schema --input` | the structured player-input schema and exact value format | `read` |");
    }
    line("| `orr set <entity> Comp.path=value ...` | direct edit, one undo entry | `scene_edit` |");
    line("| `orr spawn [--name n] [Comp=json ...]`, `despawn`, `rename`, `add`, `remove` | direct edits | `scene_edit` |");
    line("| `orr apply <label> <ops...> --check <rule>` | propose, verify, accept if all checks pass (else reject, exit 4) | `scene_edit`, `approve` |");
    line("| `orr propose <label> <ops...>` | stage a proposal, print its diff (scene unchanged) | `scene_edit` |");
    line("| `orr verify [<pN>] [--bot N \\| --idle N \\| --last-play \\| --replay f] [--check rule]` | replay check of a proposal, or the baseline of the scene | `read` |");
    line("| `orr accept <pN>` / `orr reject <pN>` / `orr proposals` / `orr diff <pN>` | decide and inspect proposals | `approve` / `scene_edit` / `read` |");
    line("| `orr history [-n N]`, `orr undo`, `orr redo` | the undo history | `read`, `scene_edit` |");
    line("| `orr sim start\\|stop\\|play\\|pause\\|step [N]\\|seek <tick>\\|speed <x>\\|state` | a play session (a copy: the scene document is untouched) | `sim_control` |");
    if input.is_some() {
        line("| `orr sim input --player <slot> '<json>'` | set a player's structured input for subsequent ticks | `sim_control` |");
        line("| `orr sim stop --replay-out <path>` | stop and write the recording to the exact local CLI path | `sim_control` |");
    }
    line("| `orr activity [--since seq] [--reads] [-f]` | the activity feed of the host | `read` |");
    line("| `orr save [--write]` | scene YAML to stdout, or write the host's scene file | `read` / `scene_edit` |");
    line("| `orr agents-md` | this guide, generated from the host | `read` |");
    line("");
    line("Ops (for `apply`, `propose`; `set` and friends are the same words as commands):");
    line("");
    line("```text");
    line("set <entity> <Comp.path>=<value>...       sset <Singleton.path>=<value>...");
    line("rename <entity> <name>                    despawn <entity>");
    line("add <entity> <Comp> [json]                remove <entity> <Comp>");
    line("spawn [--name n] [Comp=<json>...]");
    line("```");
    line("");
    if arena {
        line("Or a JSON list of op objects from `--ops-file ops.json`, or from stdin with `-`: `{\"op\":\"patch\",\"entity\":\"e_00000005\",\"component\":\"Position\",\"path\":\"pos\",\"value\":[-300,0]}` (also `insert`, `remove`, `spawn`, `despawn`, `rename`, `singleton.patch`). Example: `orr propose \"move hero\" set hero Position.pos=[-300,0]`.");
    } else {
        line("Or a JSON list of op objects from `--ops-file ops.json`, or from stdin with `-`: `{\"op\":\"patch\",\"entity\":\"e_00000005\",\"component\":\"orr_physics::Body\",\"path\":\"pos\",\"value\":[0,12.5]}` (also `insert`, `remove`, `spawn`, `despawn`, `rename`, `singleton.patch`). Example: `orr propose \"lift hero\" set hero Body.pos=[6,18] rename body_05 hero`.");
    }
    line("");
    if arena {
        line("An entity is a GUID or an exact display name (an ambiguous name is an error that lists the matches: use a GUID). Use registered component names such as `Position` and `PlayerTag`; the default Arena authoring scene is empty, so discover or create entities before editing them.");
    } else {
        line("An entity is a GUID or an exact display name (an ambiguous name is an error that lists the matches: use a GUID). A component may be written by its short name when that is unambiguous (`Body.pos` for `orr_physics::Body.pos`); an ambiguous short name is an error that lists the candidates.");
    }
    line("");

    line("## Value format");
    line("");
    line(s(&discover["value_format"]));
    line("");
    if arena {
        line("On the command line a scene value is parsed as JSON when it is JSON, else as a bare decimal (`.5`, `+3`) or string: `Position.pos=[-300,0]`, `PlayerTag.slot=0`. Structured player input must be a JSON object: axes are exact numbers and buttons are flag names such as `[\"fire\"]`. Quote arguments that contain spaces or brackets for your shell.");
    } else {
        line("On the command line a value is parsed as JSON when it is JSON, else as a bare decimal (`.5`, `+3`) or string: `pos=[6,18]`, `angle=0.5`, `orr_physics::Body.kind=dynamic`, `target=null`, `mask=\"7\"` (quote to force a string). Quote arguments that contain spaces or brackets for your shell.");
    }
    line("");
    if arena {
        line("Examples: a position vector `[-300, 0]`; an input axis `-0.5`; input buttons `[\"fire\"]` or `[]` for neutral. Numbers come back exact: `0.1` is stored as `0.1000061` (1/65536 steps), and a checksum is a string `0x` followed by 16 hex digits.");
    } else {
        line("Examples: a vector `[0, 12.5]`; a fixed-point number `-0.5` (write it as a plain decimal, never in quotes); an enum `dynamic`; an entity reference `e_00000005` or `null`; a tagged value `{ \"kind\": \"circle\", \"radius\": 0.5 }`. Numbers come back exact: `0.1` is stored as `0.1000061` (1/65536 steps), and a checksum is a string `0x` followed by 16 hex digits.");
    }
    line("");

    line("## Types of this game");
    line("");
    line("Every field is required in the scene file, but a whole-component patch may list only some fields (the rest stay). `orr schema <type>` gives the exact schema of one type.");
    line("");
    let empty = Vec::new();
    let defs = &schema["$defs"];
    for t in types["types"].as_array().unwrap_or(&empty) {
        let name = s(&t["name"]);
        line(&format!("### `{name}` ({})", s(&t["kind"])));
        line("");
        let doc = first_paragraph(s(&t["doc"]));
        if !doc.is_empty() {
            line(&doc);
            line("");
        }
        if let Some(def) = defs.get(name) {
            for l in field_lines(def, defs) {
                line(&l);
            }
            line("");
        }
    }

    if let Some(input) = input {
        line("## Structured player input");
        line("");
        line("This host exposes structured player input. Read `orr schema --input` (MCP: `get_schema` with `{\"input\":true}`) before choosing fields and values. The CLI and MCP forward exact decimal JSON without a float conversion; field validation belongs to the host.");
        line("");
        line("Start paused with `orr sim start`, then `orr sim input --player 0 '<complete JSON input object>'`, then `orr sim step N`. Setting input does not advance a tick. Input stays held until replaced; send the schema's neutral value to release it. MCP uses `sim_run` to start/step and `sim_input` with `{\"player\":0,\"value\":{...}}` to set input.");
        line("");
        line("Input schema:");
        line("```json");
        line(&serde_json::to_string_pretty(&input["schema"]).unwrap_or_default());
        line("```");
        line(s(&input["value_format"]));
        line("");
        line("`orr sim stop --replay-out session.orrp` requests the recording bytes and writes them locally where the CLI runs, overwriting that exact path. The host does not save the file. Check it with `orr verify --replay session.orrp --check recording_matches`; `orr verify --last-play --check recording_matches` also uses the host's retained recording.");
        line("");
    }

    line("## Verification");
    line("");
    line("`orr verify` (and `orr apply`) run both scenes for a number of ticks on **inputs**:");
    line("");
    line("| inputs | meaning |");
    line("|---|---|");
    if engine["verify"]["bot_available"] == true {
        line("| `--bot 300 [--seed 1] [--players 2]` | scripted players (deterministic; another seed, another play). The default. |");
        line("| `--idle 300` | no player input |");
    } else {
        line("| `--bot N` | unavailable in this host; explicitly requesting bot inputs is an error |");
        line("| `--idle 300` | no player input; the CLI default when no input source is supplied |");
    }
    if arena {
        line("| `--last-play` | the recording of the last play session stopped in this host (`orr sim` or MCP `sim_run`) |");
    } else {
        line("| `--last-play` | the recording of the last play session stopped in this host (a person's play in the editor, or `orr sim`) |");
    }
    line("| `--replay file.orrp` | a recording file |");
    line("");
    let v = &engine["verify"];
    line(&format!(
        "Limits: at most {} simulation ticks per call. One verification runs off the host thread at a time; other requests and play continue. A second verification returns `verify_busy`. Reports describe the scene/proposal captured at admission; guarded acceptance rejects later changes. The tick cap does not bound replay decoding memory or elapsed time. Tick rate {}, {} players by default. Scripted players: {}.",
        v["max_ticks"],
        v["tick_rate"],
        v["default_players"],
        if v["bot_available"] == true { "available" } else { "not available in this host (use --idle, --last-play or --replay)" }
    ));
    line("");
    line("Every scene edit changes the checksums from tick 0, so `first_divergence` is 0 for a real change. **Judge behaviour by metrics and checks**, not by divergence. An unchanged run (`identical: true`) means the change has no effect on the simulation.");
    line("");
    line("### Checks");
    line("");
    line("Repeat `--check \"<rule>\"` for each rule; the exit code is 4 when any fails.");
    line("");
    line(&format!("Grammar: `{}`", s(&v["check_grammar"])));
    line("");
    line("- `<metric>.<stat> <cmp> <number>`: `stat` is `start` (before the first tick), `final` (after the last; the default), `min`, `max` (over the sampled ticks) or `delta` (candidate final minus base final). `cmp` is `<`, `<=`, `==`, `!=`, `>=` or `>`. A metric of the candidate run unless prefixed `base:`.");
    line("- `no_divergence`: checksums equal at every tick. `no_divergence_before <tick>`. `recording_matches`: the scene reproduces the recording's checksums (`--last-play` or `--replay`).");
    line("");
    if arena {
        line("Examples: `out_of_bounds.max == 0`, `players.final == 2`, `bullets.max <= 1`, `score_0.final == 1`, `score_1.final == 0`. Choose thresholds for the scene and recording you actually tested.");
    } else {
        line("Examples: `lost_bodies.max == 0`, `mean_height >= 2.5`, `base:dynamic_bodies.start == 40`, `kinetic_energy.delta <= 10`, `entities.final == 49`.");
    }
    line("");
    if arena {
        line("`orr verify` without a proposal runs the scene alone: baseline numbers to choose sensible thresholds from. In Arena, `orr apply` without `--check` adds no implicit metric check; supply checks explicitly.");
    } else {
        line("`orr verify` without a proposal runs the scene alone: baseline numbers to choose sensible thresholds from. `orr apply` without `--check` uses `lost_bodies.max == 0` if the game reports that metric, else judges nothing.");
    }
    line("");
    line("### Metrics");
    line("");
    line("Integer (`int`) or exact fixed-point (`fixed`) numbers sampled during the run.");
    line("");
    line("| metric | kind |");
    line("|---|---|");
    let metrics = engine["metrics"].as_array().unwrap_or(&empty);
    let mut counts: Vec<&str> = Vec::new();
    for m in metrics {
        let name = s(&m["name"]);
        match name.strip_prefix("components.") {
            Some(ty) => counts.push(ty),
            None => line(&format!("| `{name}` | {} |", s(&m["kind"]))),
        }
    }
    line("");
    if !counts.is_empty() {
        line(&format!("`components.<type>` (int) counts the entities that have a component type: {}.", counts.iter().map(|c| format!("`{c}`")).collect::<Vec<_>>().join(", ")));
        line("");
    }

    line("## Exit codes and errors");
    line("");
    line("| code | meaning |");
    line("|---|---|");
    line("| 0 | ok |");
    line("| 1 | the command failed: the host answered with an error (unknown entity or type, invalid value, conflict, missing capability, ...) |");
    line("| 2 | usage error: the command line is wrong (`orr help <command>`) |");
    line("| 3 | cannot connect or authenticate (no host at the address, wrong token) |");
    line("| 4 | checks failed (`orr verify`, `orr apply`) |");
    line("");
    line("Errors go to stderr as `error: <message>` with a hint what to do; results go to stdout. A failed `orr apply` (exit 4) has already rejected its proposal and changed nothing; a failed `orr set` changed nothing either (its edits are one transaction).");
    line("");

    line("## Capabilities");
    line("");
    line("A host gives each token a set of capabilities; a command refused for lack of one says which (exit 1).");
    line("");
    line("| capability | allows |");
    line("|---|---|");
    line("| `read` | look at the scene, schema, proposals, history, activity; verify (replay runs on copies) |");
    line("| `scene_edit` | edit the scene, make and change proposals, reject them, undo |");
    line("| `approve` | accept a proposal into the scene (`orr accept`, and the last step of `orr apply`) |");
    line("| `sim_control` | start, step, seek and stop a play session |");
    line("");
    if arena {
        line("If your token lacks `approve`, `orr apply` stops after a passing verification and leaves the proposal open for a client with `approve` to accept using `orr accept` or MCP `accept_proposal`.");
    } else {
        line("If your token lacks `approve`, `orr apply` stops after a passing verification and leaves the proposal open for a person to accept in the editor.");
    }
    line("");

    line("## Conventions and pitfalls");
    line("");
    line("- Prefer GUIDs (from `orr scene`) in scripts: display names are not unique, and a rename changes them.");
    line("- Stay inside the ranges the schema states; an out-of-range or mistyped value is refused with the field named.");
    line("- Despawning an entity that another entity still points at is refused: change the reference first (same `apply`).");
    line("- While a play session runs (`orr sim`), the scene document cannot be accepted into or undone; `orr sim stop` first.");
    line("- `orr save --write` overwrites the host's scene file: do it only when asked to keep the change.");
    line("");

    line("## MCP alternative");
    line("");
    line("For clients without a shell, the same engine is available as an MCP server (`orr_mcp`, stdio) with the same workflow: `claude mcp add orrery -- orr_mcp --erp ws://127.0.0.1:7777 --token ...` (or `ORR_ERP_TOKEN` in the environment). The tools call the same ERP methods as `orr` and produce the same reports:");
    line("");
    line(&format!("Tool groups on in this guide: {}. (`orr_mcp --tools scene,propose,verify` switches groups on and off.)", groups.names().join(", ")));
    line("");
    line("| Tool | Group | Needs | What it does |");
    line("|---|---|---|---|");
    for t in tools::defs(groups) {
        line(&format!("| `{}` | {} | `{}` | {} |", t.name, t.group, t.needs, first_sentence(t.description).replace('|', "\\|")));
    }
    line("");
    if engine["verify"]["bot_available"] == true {
        line("Resources: `orrery://scene` (the scene as YAML), `orrery://schema` (JSON Schema), `orrery://agents` (this guide). A tool that fails returns `isError: true` with the engine's message. Ids are strings: proposals `p1`, entities `e_...`. The MCP workflow is `scene_overview`, `get_entity`, `get_schema`, then `propose_changes`, `verify_proposal` with `checks`, `accept_proposal` (needs `approve`), `undo`; `sim_run` drives a play session. Verification inputs are JSON there: `{\"kind\":\"bot\",\"ticks\":300,\"seed\":1}`, `{\"kind\":\"idle\",\"ticks\":300}`, `{\"kind\":\"last_play\"}`, `{\"kind\":\"replay\",\"base64\":\"...\"}`.");
    } else {
        line("Resources: `orrery://scene` (the scene as YAML), `orrery://schema` (JSON Schema), `orrery://agents` (this guide). A tool that fails returns `isError: true` with the engine's message. Ids are strings: proposals `p1`, entities `e_...`. The MCP workflow is `scene_overview`, `get_entity`, `get_schema`, then `propose_changes`, `verify_proposal` with `checks`, `accept_proposal` (needs `approve`), `undo`; `sim_run` drives a play session. This host has no bot verification: always pass explicit MCP inputs such as `{\"kind\":\"idle\",\"ticks\":300}`, `{\"kind\":\"last_play\"}`, or `{\"kind\":\"replay\",\"base64\":\"...\"}`; omitting inputs defaults to bot in the MCP tool and is refused here.");
    }
    o
}

/// The first paragraph of a doc comment, on one line.
fn first_paragraph(doc: &str) -> String {
    let para: Vec<&str> = doc.split("\n\n").next().unwrap_or("").lines().map(str::trim).collect();
    para.join(" ").split_whitespace().collect::<Vec<_>>().join(" ")
}

fn ref_name(r: &str) -> &str {
    r.rsplit('/').next().unwrap_or(r)
}

fn range(schema: &J) -> String {
    match (schema.get("minimum"), schema.get("maximum")) {
        (Some(a), Some(b)) => format!(" [{a}, {b}]"),
        _ => String::new(),
    }
}

/// A compact type text for a JSON Schema fragment.
fn type_text(schema: &J, defs: &J) -> String {
    if let Some(r) = schema.get("$ref").and_then(J::as_str) {
        return match ref_name(r) {
            "orr.Fixed" => "fixed".to_string(),
            "orr.Fixed32" => "fixed32".to_string(),
            "orr.EntityRef" => "entity reference (GUID or null)".to_string(),
            other => match defs.get(other) {
                Some(d) if d.get("enum").is_some() || d.get("oneOf").is_some() => type_text(d, defs),
                _ => format!("`{other}`"),
            },
        };
    }
    if let Some(e) = schema.get("enum").and_then(J::as_array) {
        return format!("one of {}", e.iter().map(|v| format!("`{}`", s(v))).collect::<Vec<_>>().join(" | "));
    }
    if let Some(list) = schema.get("oneOf").and_then(J::as_array) {
        let parts: Vec<String> = list
            .iter()
            .map(|v| {
                let kind = v["properties"]["kind"]["const"].as_str().unwrap_or("?");
                let fields: Vec<&str> = v["properties"].as_object().map(|m| m.keys().map(String::as_str).filter(|k| *k != "kind").collect()).unwrap_or_default();
                if fields.is_empty() { format!("`{kind}`") } else { format!("`{kind}` {{{}}}", fields.join(", ")) }
            })
            .collect();
        return format!("tagged by `kind`: {}", parts.join("; "));
    }
    match schema.get("type").and_then(J::as_str) {
        Some("array") => {
            if let Some(items) = schema.get("prefixItems").and_then(J::as_array) {
                let n = items.len();
                if n == 2 || n == 3 {
                    return format!("vec{n}{}", items.first().map(range).unwrap_or_default());
                }
            }
            let inner = schema.get("items").map(|i| type_text(i, defs)).unwrap_or_else(|| "any".into());
            let bounds = match (schema.get("minItems"), schema.get("maxItems")) {
                (Some(a), Some(b)) => format!(" ({a} to {b})"),
                _ => String::new(),
            };
            format!("list of {inner}{bounds}")
        }
        Some("number") => format!("fixed{}", range(schema)),
        Some("integer") => format!("int{}", range(schema)),
        Some("boolean") => "bool".to_string(),
        Some("string") => "string".to_string(),
        Some("object") => "object".to_string(),
        _ => match schema.get("const") {
            Some(c) => format!("`{}`", s(c)),
            None => "any".to_string(),
        },
    }
}

/// `- field: type. doc` lines of a struct type (nothing for other kinds).
fn field_lines(def: &J, defs: &J) -> Vec<String> {
    let Some(props) = def.get("properties").and_then(J::as_object) else { return Vec::new() };
    props
        .iter()
        .map(|(name, p)| {
            let doc = first_paragraph(s(&p["description"]));
            let doc = if doc.starts_with("Fixed-point number") { String::new() } else { doc };
            if doc.is_empty() { format!("- `{name}`: {}", type_text(p, defs)) } else { format!("- `{name}`: {}. {doc}", type_text(p, defs)) }
        })
        .collect()
}
