[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.0.1"
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.85"

[workspace.lints.clippy]
float_arithmetic = "warn"

[profile.release]
debug = 1
codegen-units = 1
lto = "thin"

[profile.bench]
inherits = "release"
