// @generated by orr_asset_cook format 1; do not edit.
pub const SIM_MANIFEST_SHA256: [u8; 32] = [22,121,98,27,130,150,206,163,115,193,39,243,151,245,25,220,191,174,45,62,118,2,85,15,6,73,9,182,20,163,26,58,];
const fn generated_motion(raw: i64) -> orr_asset::MotionProfileV1 {
    match orr_asset::MotionProfileV1::new(orr_fp::FP::from_raw(raw)) {
        Ok(value) => value,
        Err(_) => panic!("invalid generated motion"),
    }
}
pub static MOTION_PROFILES: [(orr_asset::AssetRef, orr_asset::MotionProfileV1); 1] = [
    (orr_asset::AssetRef::from_raw(4097), generated_motion(4096)),
];
