//! Opt-in, bounded static-asset fixture. No Arena/PhysGame or wire-format changes.
//!
//! Only [`PreparedFixture`] starts/records/verifies/seeks this game. Its private
//! simulation cannot accept debug commands, arbitrary inputs, restores or hotpatches.
//! Replays are a closed set of reviewed, generated bytes, not an untrusted loader.
//!
//! ```
//! use orr_asset_fixture::PreparedFixture;
//! let fixture = PreparedFixture::embedded()?;
//! let recording = fixture.record()?;
//! let report = fixture.verify(&recording.replay)?;
//! assert_eq!(report.checksums_checked, 300);
//! assert_eq!(fixture.seek(&recording.replay, 120)?.x.raw(), 491520);
//! # Ok::<(), orr_asset_fixture::Error>(())
//! ```
//! The generator cannot receive debug commands:
//! ```compile_fail
//! let fixture = orr_asset_fixture::PreparedFixture::embedded().unwrap();
//! fixture.record(Vec::<orr_sim::DebugCommand>::new());
//! ```
//! There is no public mutable simulation or construction bypass:
//! ```compile_fail
//! let fixture = orr_asset_fixture::PreparedFixture::embedded().unwrap();
//! fixture.start().sim.frame_mut();
//! ```
//! ```compile_fail
//! let run = orr_asset_fixture::FixtureRun::new();
//! ```
#![forbid(unsafe_code)]
#![deny(clippy::float_arithmetic, clippy::disallowed_types)]

#[cfg(feature = "audio")]
pub mod audio;

mod binding;
mod game;
mod replay;
pub use binding::{ArtifactBytes, BundleBytes, ReleaseBinding, ReleaseIndex};
pub use game::{CueEvent, FixtureRun, FixtureState, Impact, Step};
pub use replay::{Recording, EXPECTED_REPLAY_SHA256};

use orr_asset::{Domain, Manifest, ManifestEntry, MotionProfileV1, SimAsset, SimTable};
use sha2::{Digest, Sha256};

pub const GAME_ID: &str = "asset_fixture_v1";
/// Dedicated v1 fixture release label, assigned independently of asset GUIDs.
pub const GAME_CODE_ID: u64 = 0x0a2e_4a00_1001;
pub const BUILD_ID: u64 = orr_sim::frame_build_id(GAME_CODE_ID);
pub const TICK_RATE: u32 = 60;
pub const SEED: u64 = 1;
pub const TICKS: u64 = 300;
pub const PLAYER_COUNT: u8 = 1;
pub const MOTION_ID: orr_asset::AssetRef = orr_asset::AssetRef::from_raw(0x1001);
pub const IMPACT_ID: orr_asset::AssetRef = orr_asset::AssetRef::from_raw(0x2001);
pub const MAX_INPUT_BYTES: usize = 1024 * 1024;
pub const INITIAL_CHECKSUM: u64 = 0x7d81_db83_7490_e58b;

mod generated {
    include!(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../assets/fixture_v1/cooked/generated_sim.rs"
    ));
}
pub const EXPECTED_SIM_SHA256: [u8; 32] = generated::SIM_MANIFEST_SHA256;

const SIM_BYTES: &[u8] = include_bytes!("../../../assets/fixture_v1/cooked/sim.manifest.bin");
const VIEW_BYTES: &[u8] = include_bytes!("../../../assets/fixture_v1/cooked/view.manifest.bin");
const MOTION_BYTES: &[u8] = include_bytes!("../../../assets/fixture_v1/cooked/objects/a02ae51509464de11084e34346a86574191b861de2cb5cf064661b459c9bc9e4.bin");
const IMPACT_BYTES: &[u8] = include_bytes!("../../../assets/fixture_v1/cooked/objects/c26b398cc6814862c7c402b314608699121814f35ead849f8a7ac8fc6bc61c2f.bin");

#[derive(Debug)]
pub enum Error {
    Asset(orr_asset::AssetError),
    #[cfg(feature = "audio")]
    Audio(orr_audio::AudioError),
    Json(serde_json::Error),
    Replay(orr_session::ReplayError),
    Binding(&'static str),
    BudgetExceeded,
    MissingArtifact,
    DigestMismatch,
    SimBindingMismatch,
    ReleaseIdReuse,
    UntrackedReplay,
    Header(&'static str),
    Ticks,
    Input(u64),
    DebugCommand(u64),
    Checksums,
    Keyframes,
    Frame(&'static str),
    Checksum(u64),
    Verification,
    TickOutOfRange(u64),
}
impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "asset fixture: {self:?}")
    }
}
impl std::error::Error for Error {}
impl From<orr_asset::AssetError> for Error {
    fn from(value: orr_asset::AssetError) -> Self {
        Self::Asset(value)
    }
}
impl From<serde_json::Error> for Error {
    fn from(value: serde_json::Error) -> Self {
        Self::Json(value)
    }
}
impl From<orr_session::ReplayError> for Error {
    fn from(value: orr_session::ReplayError) -> Self {
        Self::Replay(value)
    }
}
pub type Result<T> = std::result::Result<T, Error>;
pub(crate) fn sha256(bytes: &[u8]) -> [u8; 32] {
    Sha256::digest(bytes).into()
}

/// Private capability produced only after binary/package/initial-frame checks.
/// It retains validated release identity; simulation uses the compiled static
/// table, never caller-owned mutable package bytes after admission.
#[derive(Debug)]
pub struct PreparedFixture {
    binding: ReleaseBinding,
    initial_checksum: u64,
}

impl PreparedFixture {
    pub fn prepare(bundle: BundleBytes<'_>, binding: &ReleaseBinding) -> Result<Self> {
        validate_identity(binding, BUILD_ID, EXPECTED_SIM_SHA256)?;
        let sim = Manifest::decode(bundle.sim_manifest, Domain::Sim)?;
        let view = Manifest::decode(bundle.view_manifest, Domain::View)?;
        view.find(IMPACT_ID)?;
        if sim.entries().any(|entry| view.find(entry.id).is_ok()) {
            return Err(Error::Asset(orr_asset::AssetError::DuplicateId));
        }
        if sha256(bundle.sim_manifest) != binding.sim_digest
            || sha256(bundle.view_manifest) != binding.view_digest
        {
            return Err(Error::DigestMismatch);
        }
        if bundle.objects.len() > orr_asset::MAX_SIM_RECORDS + orr_asset::MAX_VIEW_RECORDS {
            return Err(Error::BudgetExceeded);
        }
        // Only manifest-referenced objects belong to this bounded package.
        for object in bundle.objects {
            if !sim
                .entries()
                .chain(view.entries())
                .any(|e| e.payload_sha256 == object.sha256)
            {
                return Err(Error::Binding("unreferenced object"));
            }
        }
        binding::validate_objects(sim, bundle.objects)?;
        binding::validate_objects(view, bundle.objects)?;
        validate_table(sim, &generated::MOTION_PROFILES)?;
        let initial = game::new_simulation();
        game::validate_frame(initial.frame(), 0)?;
        let initial_checksum = initial.checksum();
        if initial_checksum != INITIAL_CHECKSUM {
            return Err(Error::Checksum(0));
        }
        Ok(Self {
            binding: binding.clone(),
            initial_checksum,
        })
    }

    /// Prepare the reviewed checked-in cooker output and separate release file.
    pub fn embedded() -> Result<Self> {
        let objects = [
            ArtifactBytes {
                sha256: sha256(MOTION_BYTES),
                bytes: MOTION_BYTES,
            },
            ArtifactBytes {
                sha256: sha256(IMPACT_BYTES),
                bytes: IMPACT_BYTES,
            },
        ];
        let bundle = BundleBytes {
            sim_manifest: SIM_BYTES,
            view_manifest: VIEW_BYTES,
            objects: &objects,
        };
        let binding = ReleaseBinding::parse(include_bytes!("../fixtures/release.json"))?;
        Self::prepare(bundle, &binding)
    }

    pub fn release(&self) -> &ReleaseBinding {
        &self.binding
    }

    /// Fresh 300-tick runner with only the fixed schedule available.
    pub fn start(&self) -> FixtureRun {
        FixtureRun::new()
    }
}

fn validate_identity(
    binding: &ReleaseBinding,
    expected_id: u64,
    expected_sim: [u8; 32],
) -> Result<()> {
    if expected_id == 0
        || orr_sim::build_hash_of(expected_id, 0) == 0
        || binding.game != GAME_ID
        || binding.game_code_id != GAME_CODE_ID
        || binding.build_id != expected_id
        || binding.sim_digest != expected_sim
    {
        return Err(Error::SimBindingMismatch);
    }
    Ok(())
}

fn validate_table(
    manifest: Manifest<'_>,
    records: &[(orr_asset::AssetRef, MotionProfileV1)],
) -> Result<()> {
    let table = SimTable::new(records)?;
    if manifest.entries().len() != records.len() {
        return Err(Error::SimBindingMismatch);
    }
    let mut entries = Vec::with_capacity(records.len());
    for (id, value) in table.entries() {
        let payload = value.encode();
        entries.push(ManifestEntry {
            id: *id,
            type_id: MotionProfileV1::TYPE_ID,
            schema_version: MotionProfileV1::SCHEMA_VERSION,
            payload_len: payload.len() as u64,
            payload_sha256: sha256(&payload),
        });
        let typed = manifest.typed_ref::<MotionProfileV1>(*id)?;
        table.resolve(typed)?;
    }
    let mut encoded = vec![0; orr_asset::manifest_encoded_len(Domain::Sim, entries.len())?];
    orr_asset::encode_manifest(Domain::Sim, &entries, &mut encoded)?;
    if encoded != manifest.as_bytes() || sha256(&encoded) != EXPECTED_SIM_SHA256 {
        return Err(Error::SimBindingMismatch);
    }
    Ok(())
}

#[cfg(test)]
mod tests;
