//! Checks that the table-driven `sin_cos` equals the CORDIC reference at
//! every input, and regenerates `src/trig_tables.rs`. This file is a test,
//! not simulation code, so plain float arithmetic is fine here.
#![allow(clippy::float_arithmetic)]

use orr_fp::FP;
use std::fmt::Write;

/// Nodes at `i / 1024` rad for `i in 0..=1609` (must match `SEG_SHIFT`).
const NODES: usize = 1610;

fn node_table(f: fn(f64) -> f64) -> Vec<i64> {
    (0..NODES)
        .map(|i| (f(i as f64 / 1024.0) * 4_294_967_296.0).round() as i64)
        .collect()
}

fn write_array(out: &mut String, name: &str, ty: &str, items: &[String], per_line: usize) {
    writeln!(out, "pub(crate) const {name}: [{ty}; {}] = [", items.len()).unwrap();
    for chunk in items.chunks(per_line) {
        writeln!(out, "    {},", chunk.join(", ")).unwrap();
    }
    writeln!(out, "];\n").unwrap();
}

#[test]
fn lut_sin_cos_equals_cordic_on_first_quadrant() {
    for raw in 0..=FP::HALF_PI.raw() {
        let a = FP::from_raw(raw);
        assert_eq!(a.sin_cos(), a.sin_cos_cordic(), "raw {raw}");
    }
}

#[test]
fn lut_sin_cos_equals_cordic_on_wide_range() {
    // Covers all quadrants, negative angles and multi-turn wrapping.
    let lim = FP::TWO_PI.raw() * 4;
    let mut raw = -lim;
    while raw <= lim {
        let a = FP::from_raw(raw);
        assert_eq!(a.sin_cos(), a.sin_cos_cordic(), "raw {raw}");
        raw += 7;
    }
    for a in [FP::MAX, FP::MIN, FP::from_raw(i64::MAX - 12345)] {
        assert_eq!(a.sin_cos(), a.sin_cos_cordic());
    }
}

/// Regenerates `src/trig_tables.rs`. Run twice after changing the node
/// layout (the first run writes the tables, the second computes the fixes
/// against them):
/// `cargo test -p orr_fp --release --test trig_lut -- --ignored`
#[test]
#[ignore]
fn generate_trig_tables() {
    let sin_tab = node_table(f64::sin);
    let cos_tab = node_table(f64::cos);

    let mut sin_fix: Vec<(u32, i8)> = Vec::new();
    let mut cos_fix: Vec<(u32, i8)> = Vec::new();
    for raw in 0..=FP::HALF_PI.raw() {
        let a = FP::from_raw(raw);
        let (cs, cc) = a.sin_cos_cordic();
        let (ls, lc) = a.sin_cos_lut_unpatched();
        let ds = cs.raw() - ls.raw();
        let dc = cc.raw() - lc.raw();
        if ds != 0 {
            sin_fix.push((raw as u32, ds as i8));
        }
        if dc != 0 {
            cos_fix.push((raw as u32, dc as i8));
        }
    }

    let fmt_fix = |v: &[(u32, i8)]| -> Vec<String> {
        v.iter().map(|(r, d)| format!("({r}, {d})")).collect()
    };
    let fmt_tab = |v: &[i64]| -> Vec<String> { v.iter().map(|x| x.to_string()).collect() };

    let mut out = String::new();
    out.push_str(
        "//! Generated by `generate_trig_tables` in `tests/trig_lut.rs`; do not edit.\n\
         //!\n\
         //! `*_TAB`: `sin`/`cos` at `i / 1024` rad, times `2^32`, rounded to nearest.\n\
         //! `*_FIX`: sorted `(raw angle, delta)` pairs where the interpolated value\n\
         //! differs from the CORDIC result; `delta` is added to the interpolated raw.\n\n",
    );
    write_array(&mut out, "SIN_TAB", "i64", &fmt_tab(&sin_tab), 6);
    write_array(&mut out, "COS_TAB", "i64", &fmt_tab(&cos_tab), 6);
    write_array(&mut out, "SIN_FIX", "(u32, i8)", &fmt_fix(&sin_fix), 6);
    write_array(&mut out, "COS_FIX", "(u32, i8)", &fmt_fix(&cos_fix), 6);

    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/src/trig_tables.rs");
    std::fs::write(path, out).unwrap();
    eprintln!("sin fixes: {}, cos fixes: {}", sin_fix.len(), cos_fix.len());
}
